name: Build

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  pull_request: {}

jobs:
  build-on-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v4
      with:
        go-version: '1.18'
    - run: ./build-on-macos.sh
    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: bin/csv2sqlite3-*
        retention-days: 3
